#This module is used by scripts generated by the user's GUI.
import time

def forward(rotations):
    '''
    Causes the robot to go forward by the number of rotations specified.
    @param rotations Number of rotations to go forward.
    '''
    raise NotImplementedError

def backward(rotations):
    '''
    Causes the robot to go backward by the number of rotations specified.
    @param rotations Number of rotations to go backward.
    '''
    raise NotImplementedError

def left():
    '''
    Turn left.
    '''
    raise NotImplementedError

def right():
    '''
    Turn right.
    '''
    raise NotImplementedError

def stop(seconds):
    '''
    Stop for a certain number of seconds.
    @param seconds Number of seconds to stop.
    '''
    time.sleep(seconds)